version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - my-network
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      cache:
        condition: service_healthy
    networks:
      - my-network
    environment:
      RATE_LIMITER_RULES: '{"abc123": {"maxRequests": 10, "limitInSeconds": 1, "blockInSeconds": 1}, "[::1]:59291": {"maxRequests": 10, "limitInSeconds": 2, "blockInSeconds": 2}}'
      STORE_KIND: redis
      REDIS_ADDRESS: cache
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      REDIS_DB: 0
      REDIS_PORT: 6379
volumes:
  cache:
    driver: local
networks:
  my-network:
    driver: bridge